server:
  port: ${TICKET_SERVICE_PORT:8082}

spring:
  application:
    name: tickets-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/eventy_tickets
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: tickets-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Plus besoin des propriétés spring.json.* ici
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

# Sécurité Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/eventy-realm}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}


  # Configuration Keycloak spécifique pour SecurityConfig.java
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://keycloak:8080}
    realm: ${KEYCLOAK_REALM:eventy-realm}